### ISSUE TITLE
Getting an error when trying to compile the code 

### ISSUE THREAD

**Issue by tall-vish** [dkosmari/calibrate-joystick#1]
I'm getting an error when I follow the instructions and try to compile the code. Fedora 40 kde. 
![Screenshot_from_2024-09-22_22-02-00](https://github.com/user-attachments/assets/876e7b74-d01f-444d-843d-be16e8ab7c87)
![Screenshot_from_2024-09-22_22-02-42](https://github.com/user-attachments/assets/4c9179f2-c830-4677-b023-777ee0582ccb)

**Comment by dkosmari** [comment]
The repository was missing the autoconf-archive macros (`ax_*.m4`), maybe that's what you were missing in your system. Not all distros install autoconf-archive by default, so I added them to the repository now.
Try starting from `./bootstrap` again after updating:
```
./bootstrap
./configure
make
```

**Comment by tall-vish** [comment]
Thank you so much for responding! I am now running into a new issue, I installed libevdevxx from your other repo and have it in the `/usr/local/lib` but I get an error when I run `./configure` that it can't find said library.
![Screenshot_20240925_045300](https://github.com/user-attachments/assets/95efb851-1fff-4c2d-a5c6-e2017fcd9096)

**Comment by dkosmari** [comment]
Try
```
./configure PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
```
I think pkg-config is searching in `/usr/lib64/pkgconfig` and `/usr/local/lib64/pkgconfig`.

**Comment by dkosmari** [comment]
There were a few broken things (in this repo, libgudevxx and libevdevxx), I recommend updating all of them.
I think I was in the middle of some refactoring, and waiting for gtkmm4 (which took forever), and forgot about it.
I'll take some time this week to do a new release.

**Comment by tall-vish** [comment]
Roger. Thank you once again for taking the time. Will give this a shot.

**Comment by dkosmari** [comment]
It's also worth a try using `make rpm` if you have rpm-build installed. The .spec files I created are tested on Mageia, but they might work on Fedora with minor modifications.

**Comment by tall-vish** [comment]
> Try
> 
> ```
> ./configure PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
> ```
> 
> I think pkg-config is searching in `/usr/lib64/pkgconfig` and `/usr/local/lib64/pkgconfig`.

This and the new repo updates did it! Thank you very much. Still having drift issues in steam but I guess I am one step closer to a solution now.
